In [20]:
import pandas as pd
df = pd.read_csv('3001.csv')
df

,channelNum,seqNum,flags,headings,heaves,pitch,roll,yaw,seconds,nano
0,0,5,15,10.80,-0.179,1.488647,-0.219727,0.0,1614008009,362000000
1,0,5,15,10.80,-0.179,1.488647,-0.225220,0.0,1614008009,372000000
2,0,5,15,10.79,-0.180,1.499634,-0.225220,0.0,1614008009,382000000
3,0,5,15,10.78,-0.180,1.505127,-0.219727,0.0,1614008009,392000000
4,0,5,15,10.77,-0.181,1.510620,-0.225220,0.0,1614008009,402000000
...,...,...,...,...,...,...,...,...,...,...
7585,0,5,15,8.27,-0.220,1.746826,-0.131836,0.0,1614008085,214000000
7586,0,5,15,8.27,-0.219,1.741333,-0.131836,0.0,1614008085,224000000
7587,0,5,15,8.27,-0.218,1.735840,-0.148315,0.0,1614008085,234000000
7588,0,5,15,8.27,-0.217,1.724854,-0.159302,0.0,1614008085,244000000
7589,0,5,15,8.26,-0.216,1.719360,-0.159302,0.0,1614008085,254000000

In [21]:



# df['PingNum'].astype(str)
# df['Channel'].astype(str)
# df['Seconds'].astype(str)
# df['Nanoseconds'].astype(str)
# df['DelayIndex'].astype(str)
df['seconds'] = df['seconds'].astype(int)
df['nano'] = df['nano'].astype(str)



# df['PingKey']= df.PingKey.str.strip('[]').astype(int)
# df['Channel']= df.Channel.str.strip('[]').astype(int)
# df['Seconds']= df.Seconds.str.strip('[]').astype(int)
# df['Angle']= df.Angle.str.strip('[]').astype('float32')
# df['DelayIndex']= df.DelayIndex.str.strip('[]').astype(int)

df['nano']= df.nano.str[:3]
df['nano'] = '.' + df['nano']
df

# pd.to_datetime(1.547559e+09, unit='s', origin='unix') 

# 2021-02-22 
df['dateTime']=pd.to_datetime(df['seconds'],  unit='s', origin='unix')
df['dateTime'] = df['dateTime'].dt.strftime('%Y-%d-%m %H:%M:%S')
df['dateTime'].astype(str)
df['dateTime'] = df['dateTime'] + df['nano']
# df['dateTime'] =  pd.to_datetime(df['dateTime'], format='%Y-%m/%d %H:%M:%S:%f') 
df['dateTime'] =  pd.to_datetime(df['dateTime'], format='%Y-%d-%m %H:%M:%S.%f') 

df = df[['channelNum', 'seqNum','flags','headings','heaves','pitch','roll','yaw','dateTime']]
df.to_csv("3000.csv",index=False)

# print((df['Angle'].iloc[1]))

df

,channelNum,seqNum,flags,headings,heaves,pitch,roll,yaw,dateTime
0,0,5,15,10.80,-0.179,1.488647,-0.219727,0.0,2021-02-22 15:33:29.362
1,0,5,15,10.80,-0.179,1.488647,-0.225220,0.0,2021-02-22 15:33:29.372
2,0,5,15,10.79,-0.180,1.499634,-0.225220,0.0,2021-02-22 15:33:29.382
3,0,5,15,10.78,-0.180,1.505127,-0.219727,0.0,2021-02-22 15:33:29.392
4,0,5,15,10.77,-0.181,1.510620,-0.225220,0.0,2021-02-22 15:33:29.402
...,...,...,...,...,...,...,...,...,...
7585,0,5,15,8.27,-0.220,1.746826,-0.131836,0.0,2021-02-22 15:34:45.214
7586,0,5,15,8.27,-0.219,1.741333,-0.131836,0.0,2021-02-22 15:34:45.224
7587,0,5,15,8.27,-0.218,1.735840,-0.148315,0.0,2021-02-22 15:34:45.234
7588,0,5,15,8.27,-0.217,1.724854,-0.159302,0.0,2021-02-22 15:34:45.244
7589,0,5,15,8.26,-0.216,1.719360,-0.159302,0.0,2021-02-22 15:34:45.254

In [14]:
df.dtypes

channelNum             int64
seqNum                 int64
flags                  int64
headings             float64
heaves               float64
pitch                float64
roll                 float64
yaw                  float64
seconds                int32
nano                  object
dateTime      datetime64[ns]
dtype: object